### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by lzb0530** [UangTsui/json#1]

**Comment by UangTsui** [comment]
拉取代码后直接使用浏览器打开 index.html 就可以使用了，或使用网页版的！

**Comment by lzb0530** [comment]
我有一个xml文件，我想在我的回调函数里面把它处理成json然后使用

**Comment by UangTsui** [comment]
打开 index.html 后将你 xml 文件内容拷贝到左侧文本框，右侧会自动转换为 json

**Comment by lzb0530** [comment]
我想调用你的文件或者函数，在代码里使用它方法转成json数据

**Comment by UangTsui** [comment]
请使用 js 下的 jquery.xml2json.js 进行转换，具体可以看官方 api 或参考此项目的源码！

**Comment by lzb0530** [comment]
好的，了解了谢谢！
